# fly.toml app configuration file generated for mandyle on 2023-08-22T20:03:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mandyle"
primary_region = "yyz"
console_command = "/rails/bin/rails console"

[env]

[build]

[deploy]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
